// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXCqckU6Qkys5CXv3iSwtxNcREEFZagt0',
    appId: '1:871506694746:web:df24bea61d599fd2923e63',
    messagingSenderId: '871506694746',
    projectId: 'bahcem',
    authDomain: 'bahcem-73101.firebaseapp.com',
    storageBucket: 'bahcem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFeZ6mOPZsuZvot5JDPjwpZmu0IZMmPVc',
    appId: '1:871506694746:android:b6e2686522f62864923e63',
    messagingSenderId: '871506694746',
    projectId: 'bahcem',
    storageBucket: 'bahcem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS1T6rAQxkIoeZyf590h1CJl1f6xY0w2E',
    appId: '1:871506694746:ios:fbcc04e3dd88b51e923e63',
    messagingSenderId: '871506694746',
    projectId: 'bahcem',
    storageBucket: 'bahcem.appspot.com',
    iosBundleId: 'com.example.bahcem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS1T6rAQxkIoeZyf590h1CJl1f6xY0w2E',
    appId: '1:871506694746:ios:cbec002036b5bbe8923e63',
    messagingSenderId: '871506694746',
    projectId: 'bahcem',
    storageBucket: 'bahcem.appspot.com',
    iosBundleId: 'com.example.bahcem.RunnerTests',
  );
}
